---
version: '3.4'
services:
  api:
    image: flaskapp:1.0.0
    build:
      context: /app/h-backend
      dockerfile: flask.dockerfile  # Adjust this according to your Dockerfile location
    ports:
      - "5000:5000"  # Adjust the port mapping if needed
    depends_on:
      - db
    environment:
      CLOUD_NAME: "dlw7wjlp3"
      CLOUD_API_KEY: "824519396937353"
      CLOUD_API_SECRET: "sAEU2wLub6Gq9Woj8YIiZLKtjpY"
      WEAVIATE_URL: "http://weaviate:8080"
      POSTGRE_HOST: "host.docker.internal"
      POSTGRE_PASSWORD: "admin123"
      BASE_ADDRESS: "0.0.0.0"
  db: 
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    ports:
      - 5433:5433
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: ridmy/weaviate:1.23.3
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
  i2v-neural:
    image: ridmy/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'
  client:
    image: hush-client
    build:
      context: /app/h-frontend  # Adjust this path to the location of your React TypeScript app
      dockerfile: Dockerfile  # Adjust this according to your React Dockerfile location
    ports:
      - "3000:3000"  # Adjust the port mapping if needed
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://localhost:5000


volumes: 
  pgdata: {}