version: '3.4'

services:
  - type: web
    name: h-backend
    buildCommand: pip install poetry && poetry install && poetry add pyproject.toml
    startCommand: poetry run python -m backend  # replace with the actual command to start your application
    envVars:
      - key: CLOUD_NAME
        value: "dlw7wjlp3"
      - key: CLOUD_API_KEY
        value: "824519396937353"
      - key: CLOUD_API_SECRET
        value: "sAEU2wLub6Gq9Woj8YIiZLKtjpY"
      - key: WEAVIATE_URL
        fromService:
          name: weaviate
          property: "https://h-weaviate.onrender.com"
      - key: POSTGRE_HOST
        value: "host.docker.internal"
      - key: POSTGRE_PASSWORD
        value: "admin123"
      - key: BASE_ADDRESS
        value: "0.0.0.0"

  - type: web
    name: h-frontend
    buildCommand: ./h-frontend
    startCommand: npm start  # replace with the actual command to start your frontend
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: api
          property: "https://hu-backend.onrender.com"

  - type: web
    name: h-weaviate
     # replace with the actual command to start Weaviate
    envVars:
      - key: IMAGE_INFERENCE_API
        value: 'https://im2vec-pytorch.onrender.com'
      - key: QUERY_DEFAULTS_LIMIT
        value: '25'
      - key: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
        value: 'true'
      - key: PERSISTENCE_DATA_PATH
        value: '/var/lib/weaviate'
      - key: DEFAULT_VECTORIZER_MODULE
        value: 'img2vec-neural'
      - key: ENABLE_MODULES
        value: 'img2vec-neural'
      - key: CLUSTER_HOSTNAME
        value: 'node1'

  - type: worker
    name: im2vec-pytorch
    envVars:
      - key: ENABLE_CUDA
        value: '0'

databases:
  - name: db


