services:
  - type: web
    name: api
    runtime: docker
    dockerfilePath: ./h-backend/flask.dockerfile
    envVars:
      - key: CLOUD_NAME
        value: "dlw7wjlp3"
      - key: CLOUD_API_KEY
        value: "824519396937353"
      - key: CLOUD_API_SECRET
        value: "sAEU2wLub6Gq9Woj8YIiZLKtjpY"
      - key: WEAVIATE_URL
        fromService:
          type: web
          name: weaviate
          property: "http://weaviate:8080"
      - key: POSTGRE_HOST
        value: "host.docker.internal"
      - key: POSTGRE_PASSWORD
        value: "admin123"
      - key: BASE_ADDRESS
        value: "0.0.0.0"
    ports:
      - 5000:5000
    dependsOn:
      - name: db

  - type: web
    name: client
    runtime: docker
    dockerfilePath: ./h-frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: api
          property: "http://localhost:3000"
    ports:
      - 3000:3000
    dependsOn:
      - name: api

  - type: web
    name: weaviate
    runtime: docker
    repo: semitechnologies/weaviate
    envVars:
      - key: IMAGE_INFERENCE_API
        value: 'http://i2v-neural:8080'
      - key: QUERY_DEFAULTS_LIMIT
        value: '25'
      - key: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
        value: 'true'
      - key: PERSISTENCE_DATA_PATH
        value: '/var/lib/weaviate'
      - key: DEFAULT_VECTORIZER_MODULE
        value: 'img2vec-neural'
      - key: ENABLE_MODULES
        value: 'img2vec-neural'
      - key: CLUSTER_HOSTNAME
        value: 'node1'
    ports:
      - 8080:8080
      - 50051:50051

  - type: web
    name: i2v-neural
    runtime: docker
    repo: semitechnologies/img2vec-pytorch:resnet50
    envVars:
      - key: ENABLE_CUDA
        value: '0'

databases:
  - name: db
    databaseName: postgres
    user: postgres
    envVars:
      - key: POSTGRES_PASSWORD
        value: "$=w_$%v7M=`|;[n92}$YJ$8XGTk_hfz6! "
    ports:
      - 5433:5433
    volumes:
      - name: pgdata
        mountPath: /var/lib/postgresql/data

volumes:
  - name: pgdata