version: '3.4'

services:
  - type: web
    name: api
    buildCommand: pip install poetry && poetry install && poetry add pyproject.toml
    startCommand: poetry run python -m backend  # replace with the actual command to start your application
    envVars:
      - key: CLOUD_NAME
        value: "dlw7wjlp3"
      - key: CLOUD_API_KEY
        value: "824519396937353"
      - key: CLOUD_API_SECRET
        value: "sAEU2wLub6Gq9Woj8YIiZLKtjpY"
      - key: WEAVIATE_URL
        fromService:
          name: weaviate
          property: "http://weaviate:8080"
      - key: POSTGRE_HOST
        value: "host.docker.internal"
      - key: POSTGRE_PASSWORD
        value: "admin123"
      - key: BASE_ADDRESS
        value: "0.0.0.0"

  - type: web
    name: client
    buildCommand: ./h-frontend
    startCommand: npm start  # replace with the actual command to start your frontend
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: api
          property: "http://localhost:5000"

  - type: web
    name: weaviate
    startCommand: ./start_weaviate.sh  # replace with the actual command to start Weaviate
    envVars:
      - key: IMAGE_INFERENCE_API
        value: 'http://i2v-neural:8080'
      - key: QUERY_DEFAULTS_LIMIT
        value: '25'
      - key: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
        value: 'true'
      - key: PERSISTENCE_DATA_PATH
        value: '/var/lib/weaviate'
      - key: DEFAULT_VECTORIZER_MODULE
        value: 'img2vec-neural'
      - key: ENABLE_MODULES
        value: 'img2vec-neural'
      - key: CLUSTER_HOSTNAME
        value: 'node1'

  - type: worker
    name: i2v-neural
    envVars:
      - key: ENABLE_CUDA
        value: '0'

databases:
  - name: db
    type: postgres
    user: postgres
    envVars:
      - key: POSTGRES_PASSWORD
        value: "$=w_$%v7M=`|;[n92}$YJ$8XGTk_hfz6! "

volumes:
  - name: pgdata

